name: slideparty_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.15.1 <3.0.0'

publish_to: 'none'

dependencies:
  mongo_dart: ^0.7.4
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_web_socket: ^1.0.1
  uuid: ^3.0.5
  slideparty_socket:
    path: "../slideparty_socket"

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test: ^1.15.0
  test_process: ^2.0.0
